### ISSUE TITLE
Fail with '_socketobject' object has no attribute 'set_tlsext_host_name'

### ISSUE THREAD

**Issue by Onlinehead** [passslot/passslot-python-sdk#1]
When i try to use it, i got an error:
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    pspass = engine.create_pass_from_template(passTemplateId, values, images)
  File "/home/onlinehead/passslot-python-sdk/passslot.py", line 55, in create_pass_from_template
    return self.__create_pass(resource, values, images)
  File "/home/onlinehead/passslot-python-sdk/passslot.py", line 77, in __create_pass
    result = self.__call('post', resource, content, multipart)
  File "/home/onlinehead/passslot-python-sdk/passslot.py", line 119, in __call
    response = self.session.request(method, self.base_url + resource, headers=headers, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/sessions.py", line 383, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/sessions.py", line 486, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/packages/urllib3/connection.py", line 164, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.2.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 378, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'

That happend because Ubuntu 12.04 (that is my server's OS) has old pyOpenSSL library which not accept attribute 'set_tlsext_host_name'.
For fix that, you need to add dependence pyOpenSSL >= 0.13.
On Ubuntu for update pyOpenSSL use pip, you also need to install libffi-dev and remove python-openssl by apt. 
Add that to instruction.
Thanks!

**Comment by passslot** [comment]
Hi @Onlinehead 

Thanks for sharing this bug and also providing the solution.
We have added the missing dependency.

Kind regards

**Comment by tuwid** [comment]
thnx :D

**Comment by raj454raj** [comment]
Any developments on this issue. I am getting same error while using it in web2py. Here's the traceback. Please help.

> Traceback (most recent call last):
  File "/home/raj/development/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
  File "/home/raj/development/web2py/applications/crowdsourcing/controllers/search.py", line 61, in <module>
  File "/home/raj/development/web2py/gluon/globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "/home/raj/development/web2py/applications/crowdsourcing/controllers/search.py", line 36, in index
    r = requests.get(url = url, auth = oauth, proxies = proxy)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 539, in urlopen
    self._prepare_proxy(conn)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 727, in _prepare_proxy
    conn.connect()
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'

**Comment by raj454raj** [comment]
@Onlinehead : My error log. 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/api.py", line 68, in get
>     return request('get', url, *_kwargs)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
>     response = session.request(method=method, url=url, *_kwargs)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
>     r = adapter.send(request, *_kwargs)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
>     timeout=timeout
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
>     body=body, headers=headers)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
>     self._validate_conn(conn)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
>     conn.connect()
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
>     ssl_version=resolved_ssl_version)
>   File "/home/raj/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
>     cnx.set_tlsext_host_name(server_hostname)
> AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'

Please help. I am in urgent use of this.

**Comment by passslot** [comment]
Which pyOpenSSL version have you installed? Please verify that it is at least version 0.13

**Comment by raj454raj** [comment]
How do I check it. Is it a python module?

**Comment by raj454raj** [comment]
How do I upgrade it. pip freeze gives me version 0.11
sudo pip install pyOpenSSL --upgrade gives this - 

> Downloading/unpacking pyOpenSSL from https://pypi.python.org/packages/py2.py3/p/pyOpenSSL/pyOpenSSL-0.15.1-py2.py3-none-any.whl#md5=8ca6d74b42df1e3178e59e9b08746d77
>   Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB): 102kB downloaded
> Downloading/unpacking six>=1.5.2 from https://pypi.python.org/packages/3.3/s/six/six-1.9.0-py2.py3-none-any.whl#md5=9ac7e129a80f72d6fc1f0216f6e9627b (from pyOpenSSL)
>   Downloading six-1.9.0-py2.py3-none-any.whl
> Requirement already up-to-date: cryptography>=0.7 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL)
> Requirement already up-to-date: idna in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Requirement already up-to-date: pyasn1 in /usr/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Requirement already up-to-date: cffi>=0.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyOpenSSL)
> Downloading/unpacking pycparser from https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935 (from cffi>=0.8->cryptography>=0.7->pyOpenSSL)
>   Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
>   Running setup.py (path:/tmp/pip_build_root/pycparser/setup.py) egg_info for package pycparser
>     warning: no previously-included files matching 'yacctab._' found under directory 'tests'
>     warning: no previously-included files matching 'lextab._' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab._' found under directory 'examples'
>     warning: no previously-included files matching 'lextab._' found under directory 'examples'
> Installing collected packages: pyOpenSSL, six, pycparser
>   Found existing installation: pyOpenSSL 0.15
>     Uninstalling pyOpenSSL:
>       Successfully uninstalled pyOpenSSL
>   Found existing installation: six 1.5.2
>     Uninstalling six:
>       Successfully uninstalled six
>   Found existing installation: pycparser 2.10
>     Can't uninstall 'pycparser'. No files were found to uninstall.
>   Running setup.py install for pycparser
>     warning: no previously-included files matching 'yacctab._' found under directory 'tests'
>     warning: no previously-included files matching 'lextab._' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab._' found under directory 'examples'
>     warning: no previously-included files matching 'lextab._' found under directory 'examples'
>     Build the lexing/parsing tables
> Successfully installed pyOpenSSL six pycparser
> Cleaning up...

But still the version remains the same

**Comment by dgoldstein0** [comment]
You are probably using the wrong pip.  Since systems have multiple installs
of python (e.g. it's common on Ubuntu), and you need to install packages
for the right python install; this should be a matter of choosing the right
pip to use.

**Comment by raj454raj** [comment]
Yes I know I am using the wrong pip. How do I upgrade it is my question? Please help

**Comment by dgoldstein0** [comment]
No I mean you likely have two versions of pip on your system, and the
default one is probably not what you want to be using.

Try running "locate pip" and see what you find.

**Comment by raj454raj** [comment]
> Try running "locate pip" and see what you find.

Gives me a lot of lines since it searches all instances of pip
What if I want to remove all versions of pip in the system and then install new one
